### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cag**

### CODE REVIEW

**Comment by cgewecke** [comment]
@cag The 'reporter not found' seem to be something to do with Truffle 5.0.30. Everything is ok on 5.0.29.

**Comment by cag** [comment]
Oddly enough, my local copy runs just fine.

**Comment by cgewecke** [comment]
@cag Hmm, you're still getting a 500 server error from codechecks though. Super weird. I wonder if your account somehow got scrambled. The only thing I can think of for fixing that is turning it on/off again and re-pasting the CC_SECRET in the travis env.

In #62 I got an error from codechecks about not being authorized and I think that *should* also be working - e.g. you should be able to PR from a fork and get a report.

**Comment by cag** [comment]
Might have been the project name change...

**Comment by krzkaczor** [comment]
@cag Hey! Codechecks backend team here 🤣  I am glad that it works now. 

Could you help me to understand what exactly happened so I can fix it on my end? Did you just renamed repository or was it moved to the other org?

Thanks!

**Comment by cag** [comment]
@krzkaczor I just renamed the repository. I remember seeing in the Codechecks dash that this project was still named `hg-contracts` there.

**Pull request merged**
