### PR TITLE
Implement split and merge for ERC-1155 collateral tokens

### LINKED ISSUE #56: Allow ERC-1155 as collateral
This would entail changing the makeup of the position ID hash payload, adding a value for distinguishing between ERC-20 and ERC-1155 tokens, as well as a value to identify the ID of a particular ERC-1155 token.

### PR DESCRIPTION
**Pull request by cag**
Closes #56

### CODE REVIEW

**Comment by cgewecke** [comment]
@cag Sorry, spying on this repo to see when codechecks stuff breaks (and it did!) 

I just ran clean [here](https://github.com/cgewecke/eth-gas-reporter/pull/167/checks) and am wondering if your failure was a random server glitch or something deeper....

**Comment by cag** [comment]
Hey! I think maybe this is because the contracts won't lint anymore. I dunno why though, but the linter crashes. Let me try removing the linting from the CI script.

**Comment by cgewecke** [comment]
Oh no. I'm going to publish a patch that catches the error and exits `0` so at least this doesn't fail CI. Also pinged codechecks to ask if they can see anything in the server logs. 

Sorry about this and thanks for being (willing to be) experimented on.

**Comment by cgewecke** [comment]
`0.2.9` has the graceful exit and some debugging logs... if you hit rerun on the PR build it might go green.

**Comment by cgewecke** [comment]
Lastly - I forked this repo to reproduce and got a report ok - [here](https://github.com/cgewecke/conditional-tokens-contracts/pull/2/checks?check_run_id=181184102). 

One thing I did was explicitly uninstall/re-install the gas reporter because greenkeeper lock wasn't letting it float up to latest. But idk if that's really the issue...

**Pull request merged**
